name: bt_controller_v2
description: A watch controller app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.4.0
  fl_chart: ^0.60.0
  image_picker: ^0.8.7+4
  image: ^4.0.17
  permission_handler: ^10.4.0
  notification_listener_service: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

